name: Daily Musings
favicon: null
layout_spectrum: 0.2675959568005055
typography_spectrum: 0.861498718848452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8459920755121857
  lightness: 0.21643849834799767
  saturation: 0.47762204403989017
  rhythmicContrast: 0.464431706815958
purpose: []
